### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by risingupfitness** [jasonlewis72/risingupfitness#2]
Things to change on the website

Homepage
•	Please change the picture that is on Personal training to a picture of someone being trained by a PT
•	Group fitness timetable (down right hand side) a bit smaller. Have a heading that says TODAYS CLASSES. Underneath put a small widget for FIT & STRONG (see below). It may look better in white. Put a title above it that says FIT & STRONG.
 
•	Group fitness photo to change _ I will provide
•	Drop the copy down to have a bigger gap under tiles, maybe make the font bigger, seems like there is a large gap at the bottom of the page
•	Change OPENING HOURS to STAFFED HOURS – new staffed hours are Mon-Thursday 9am-9pm, Friday 9am-8:30pm, Saturday 8am-1pm

**Comment by jasonlewis72** [comment]
Homepage
• Please change the picture that is on Personal training to a picture of someone being trained by a PT
>> Done

• Group fitness timetable (down right hand side) a bit smaller. Have a heading that says TODAYS CLASSES. Underneath put a small widget for FIT & STRONG (see below). It may look better in white. Put a title above it that says FIT & STRONG.
>> Have added in Fit n Strong - Need to fix some issues with the timetable so have hidden it today till its sorted

• Group fitness photo to change _ I will provide
>> Please send this through when you have it

• Drop the copy down to have a bigger gap under tiles, maybe make the font bigger, seems like there is a large gap at the bottom of the page
• Change OPENING HOURS to STAFFED HOURS – new staffed hours are Mon-Thursday 9am-9pm, Friday 9am-8:30pm, Saturday 8am-1pm
>> Done

**Comment by risingupfitness** [comment]
The sash on the image slider is cut short, it needs to continue further left

**Comment by risingupfitness** [comment]
Please make one of the image slider's the myzone image that appears on the top of the myzone page. Please include a more info button that links to the myzone page.

**Comment by risingupfitness** [comment]
I would like 3 image slider pics

1. $12.95 special (I will send you shortly - Please add text "Limited time only" also add a call now button, linking through to the contact us page
2. Fit & Strong (use current image) Add text under FIT & STRONG - "take your fitness to the next level". Add a more information button linking to the fit and strong page
3. Gym Picture (use current image - treadmills etc.) Add text "Personal Training at its finest" include a link to the personal training page

**Comment by jasonlewis72** [comment]
Hi Baron

The 3 image slider pics have been updated

**Comment by jasonlewis72** [comment]
I've removed the sash on the image slider and have updated the header image
