### ISSUE TITLE
New Page – MYZONE 

### ISSUE THREAD

**Issue by risingupfitness** [jasonlewis72/risingupfitness#4]
MYZONE – Making Movement Measurable
MYZONE improves you RESULTS, by providing an accurate monitoring system to encourage effort during physical activity.
•	Track your progress after every workout
•	See where you are strong and where you can improve
•	Join fun challenges, earn activity points and more
Workout Stats
Myzone records your workout stats including your time in different heart rate zones, the calories you burn and the MEP’s you earn.  On top of this the Tanita scales will record all of your important body metric details including your body fat percentage, your health age, your BMI, your weight so that you can set your personal health goals and access them 24/7 through your personal Myzone account page.
Earn Points
MYZONE Effort Points (MEPs) are a new metric for measuring physical activity. MEPs accumulate for every minute of activity that a user spends in the 5 effort (intensity) zones based on one’s individual maximum heart rate. The more effort that is put in, the more MYZONE Effort points are earned.
Challenges
Challenge friends, family or members of your gym with MYZONE challenges.
Set the target or set the date to achieve the most MEPS or calories to burn and Myzone will wirelessly track and report on your progress and leader board with your competition.
You can challenge anyone with Myzone around the world.  So if you get motivated by competition, invite your friends and step up to the MYZONE challenge.
Progress Tracking
Success is measured by effort.  Your effort is measured by Myzone.
Set your personal health goals and MYZONE will automatically update your progress in one of the many measurements including calories, muscle mass, BMI, weight, body fat percentage, MEPS and much more.
After each workout you will receive an automated email providing an overview to your workout to give you the most important motivation of them all ‘feedback that you are making progress’ towards your health and fitness goal.

**Comment by jasonlewis72** [comment]
Please review and if ok - please close

**Comment by risingupfitness** [comment]
the top picture needs to be fixed. If we delete the myzone logo from it as it is being cut off.The Fit and Strong Widget can be removed from this page

**Comment by jasonlewis72** [comment]
- Have updated the background image as discussed and removed the color squares
- Have removed the widget

**Comment by risingupfitness** [comment]
Can you please remove the image from the top of the screen and replace it with the gym image from the image slider

**Comment by jasonlewis72** [comment]
Done
