### ISSUE TITLE
Personal Training page

### ISSUE THREAD

**Issue by risingupfitness** [jasonlewis72/risingupfitness#5]
http://risingupfitness.com.au/concrete5/index.php/personal-training

•	Include PT numbers on each of their profiles
o	Lisa 0408 525 068
o	Gary 0412 262 955
o	Stella 0414519311
o	Kelly 0435 143 463

**Comment by jasonlewis72** [comment]
These have been added in - Please confirm layout is ok - if so - please close issue

**Comment by risingupfitness** [comment]
Great!
