### ISSUE TITLE
FIT & STRONG page

### ISSUE THREAD

**Issue by risingupfitness** [jasonlewis72/risingupfitness#6]
http://risingupfitness.com.au/concrete5/index.php/fit-and-strong

•	Revert to original layout you created, include schedule widget like on front page

**Comment by jasonlewis72** [comment]
This has been update - Please confirm this is ok

**Comment by risingupfitness** [comment]
In the session times can you please add 6pm it is missing the 6.

**Comment by jasonlewis72** [comment]
Done
