### ISSUE TITLE
Contact Us page

### ISSUE THREAD

**Issue by risingupfitness** [jasonlewis72/risingupfitness#7]
http://risingupfitness.com.au/concrete5/index.php/contact

	Fix staffed hours
•	Include copy
o	At Rising Up Fitness we want to help you achieve your goals. To get more information and to speak to one of our friendly staff, fill in the form below or just give us a call

**Comment by jasonlewis72** [comment]
Hi Baron - I've updated the copy here - did you want me to split out the Staffed Hours for each day?

**Comment by risingupfitness** [comment]
That would be great :)

**Comment by jasonlewis72** [comment]
Done - Please confirm ok - If so, please close issue

**Comment by risingupfitness** [comment]
Can you please include on the address (Next to Harvey Norman). It helps people understnad exactly where we are. Could you add this on the bottom of each page as well as on the contact us page.
Thanks

**Comment by jasonlewis72** [comment]
Done
